# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
loader_version=0.19.3
# Mod Properties
mod_version=1.21.4-Fabric-1.5.0-A
maven_group=io.github.seraphina
archives_base_name=infinity_item_editor_re
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.119.4+1.21.4
